### ISSUE TITLE
for Navigation controller

### ISSUE THREAD

**Issue by dynamicdreamz1** [rushairer/BubbleTransitionForObjC#1]
Hello, I have tried transition controller for Navigation controller but its not working for navigation controller. Can you guide me?
 self.BTModalViewController = [[ModalViewController alloc] init];
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:self.BTModalViewController];
    nav.transitioningDelegate = self;
    nav.modalPresentationStyle = UIModalPresentationCustom;
    [self presentViewController:nav animated:YES completion:nil];

**Comment by dynamicdreamz1** [comment]
ok its working, this way
self.BTModalViewController = [[ModalViewController alloc] init];
self.BTModalViewController.transitioningDelegate = self;
self.BTModalViewController.modalPresentationStyle = UIModalPresentationCustom;

UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:self.BTModalViewController];
nav.transitioningDelegate = self;
nav.modalPresentationStyle = UIModalPresentationCustom;
[self presentViewController:nav animated:YES completion:nil];

Many Thanks,,, :)

**Comment by rushairer** [comment]
@dynamicdreamz1 Thanks for your issue.
